### ISSUE TITLE
[BUG]ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by itsamegaming** [rdeepak2002/reddit-place-script-2022#104]

**Comment by Risewill23** [comment]
can you post the log?

**Comment by itsamegaming** [comment]
[02-Apr-22 16:06:47] :: [INFO] - place-script started
[02-Apr-22 16:06:47] :: [INFO] - Loaded image size: (800, 80)
[02-Apr-22 16:06:48] :: [INFO] - Thread #0 ::
[02-Apr-22 16:06:48] :: [INFO] - Thread #0 :: Refreshing access token
[02-Apr-22 16:06:49] :: [INFO] - Received new access token: 17731************
[02-Apr-22 16:06:49] :: [INFO] - Getting board
[02-Apr-22 16:06:50] :: [INFO] - Received board image: https://hot-potato.reddit.com/media/canvas-images/1648930013709-0-f-bN9iY4gW.png
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\rl800\Downloads\mods\reddit-place-script-2022-main\main.py", line 424, in task
    current_r, current_c, new_rgb = self.get_unset_pixel(
  File "C:\Users\rl800\Downloads\mods\reddit-place-script-2022-main\main.py", line 281, in get_unset_pixel
    new_rgb = self.closest_color(target_rgb)
  File "C:\Users\rl800\Downloads\mods\reddit-place-script-2022-main\main.py", line 73, in closest_color
    r, g, b = target_rgb
ValueError: too many values to unpack (expected 3)
[02-Apr-22 16:06:50] :: [INFO] - Thread #1 ::
[02-Apr-22 16:06:50] :: [INFO] - Thread #1 :: Refreshing access token
[02-Apr-22 16:06:51] :: [INFO] - Received new access token: 62688************
[02-Apr-22 16:06:51] :: [INFO] - Getting board
[02-Apr-22 16:06:52] :: [INFO] - Received board image: https://hot-potato.reddit.com/media/canvas-images/1648930015636-0-f-LwsZj2H4.png
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\rl800\Downloads\mods\reddit-place-script-2022-main\main.py", line 424, in task
    current_r, current_c, new_rgb = self.get_unset_pixel(
  File "C:\Users\rl800\Downloads\mods\reddit-place-script-2022-main\main.py", line 281, in get_unset_pixel
    new_rgb = self.closest_color(target_rgb)
  File "C:\Users\rl800\Downloads\mods\reddit-place-script-2022-main\main.py", line 73, in closest_color
    r, g, b = target_rgb
ValueError: too many values to unpack (expected 3)

**Comment by ixi2101** [comment]
#107 
Will refix this

**Comment by itsamegaming** [comment]
So wait am i doing something wrong or is this a bug? (sorry im kinda new to all of this)

**Comment by Randomblock1** [comment]
Fixed
