### ISSUE TITLE
[BUG] Image index out of range for no reason

### ISSUE THREAD

**Issue by NielsVandenEynde** [rdeepak2002/reddit-place-script-2022#106]
# Bug Report Form

## Checklist

- [ x] I am using the latest version of the code.
- [x ] I am absolutely sure I read the README in its entirety.
- [x ] I have made sure this is not a duplicate issue.
- [ x] I have filled out this form correctly.

## Describe the bug

I have a correctly filled in config.json and get an image index out of range
```
[02-Apr-22 22:07:29] :: [INFO] - Loaded image size: (30, 45)
[02-Apr-22 22:07:30] :: [INFO] - Thread #0 ::
[02-Apr-22 22:07:30] :: [INFO] - Thread #0 :: Refreshing access token
[02-Apr-22 22:07:31] :: [INFO] - Received new access token: 81311************
[02-Apr-22 22:07:31] :: [INFO] - Getting board
[02-Apr-22 22:07:32] :: [INFO] - Received board image: https://hot-potato.reddit.com/media/canvas-images/1648930052275-0-f-FPSRDsx6.png
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File ".\main.py", line 427, in task
    current_c,
  File ".\main.py", line 282, in get_unset_pixel
    if pix2[x + self.pixel_x_start, y + self.pixel_y_start] != new_rgb:
IndexError: image index out of range

(env) PS C:\Users\niels\Downloads\reddit-place-script-2022-main\reddit-place-script-2022-main>
```

My config file looks like this:

{
    "image_start_coords": [1801, 61],
    "thread_delay": 2,

    "workers": {
        "xx": {
            "password": "xx",
            "client_id": "xxx",
            "client_secret": "xx",
            "start_coords": [0, 0]
        }

    }
}

**Comment by Risewill23** [comment]
the second half is not supported yet sorry

**Comment by NielsVandenEynde** [comment]
OK nvm I'm a dumbass I mixed up the coords

**Comment by BlazingFire007** [comment]
@Risewill23 Any way to easily add the second half? Or is it difficult?

**Comment by NielsVandenEynde** [comment]
> the second half is not supported yet sorry

What is the issue with the second half? I could take a look but I'm not up to speed with this project
