### ISSUE TITLE
[BUG] Error: image index out of range

### ISSUE THREAD

**Issue by sean-phyx** [rdeepak2002/reddit-place-script-2022#112]
# Bug Report Form

## Checklist

- [X] I am using the latest version of the code.
- [X] I am absolutely sure I read the README in its entirety.
- [X] I have made sure this is not a duplicate issue.
- [X] I have filled out this form correctly.

## Describe the bug

Image index out of range. Traceback:
[02-Apr-22 21:23:34] :: [INFO] - place-script started
[02-Apr-22 21:23:34] :: [INFO] - Loaded image size: (7, 5)
[02-Apr-22 21:23:35] :: [INFO] - Thread #0 ::
[02-Apr-22 21:23:35] :: [INFO] - Thread #0 :: Refreshing access token
[02-Apr-22 21:23:36] :: [INFO] - Received new access token: 16788************
[02-Apr-22 21:23:36] :: [INFO] - Getting board
[02-Apr-22 21:23:37] :: [INFO] - Received board image: https://hot-potato.reddit.com/media/canvas-images/1648931016965-0-f-OTs4P3Et.png
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 433, in task
    current_r, current_c, new_rgb = self.get_unset_pixel(
  File "main.py", line 288, in get_unset_pixel
    if pix2[x + self.pixel_x_start, y + self.pixel_y_start] != new_rgb:
IndexError: image index out of range

## Expected behavior

Not be out of range. Not sure if its the image although its just a small png 8 bit mario image so I feel that shouldn't be the problem. Its of size (7,5)px

## Additional context

Not sure if its my end or the program itself.?

**Comment by natthawk** [comment]
You're trying to access pixels on the expanded canvas; support for this has not been added to main yet.

**Comment by sean-phyx** [comment]
Alrighty, thank you and apologies for the duplicate
