### ISSUE TITLE
Error when running main.py

### ISSUE THREAD

**Issue by orion-t** [rdeepak2002/reddit-place-script-2022#115]
Traceback (most recent call last):
  File "/Users/oriontomasi/Documents/reddit-place-script-2022/main.py", line 497, in <module>
    client = PlaceClient()
  File "/Users/oriontomasi/Documents/reddit-place-script-2022/main.py", line 44, in __init__
    if self.json_data["unverified_place_frequency"] is not None
KeyError: 'unverified_place_frequency'

when I run main.py. I filled out everything, the files seem alright

**Comment by itsamegaming** [comment]
"unverified_place_frequency": "False",
put that at the beginning of your config

**Comment by Dracula56** [comment]
> "unverified_place_frequency": "False",

This fixed it for me, thank you.
