### ISSUE TITLE
keep getting "Expecting value: line 1 column 2 (char 1)"

### ISSUE THREAD

**Issue by NotNer0** [rdeepak2002/reddit-place-script-2022#12]
anytime I run main.py, it comes back with this
`Traceback (most recent call last):
  File "D:\download\reddit-place-script-2022-1.0.0\reddit-place-script-2022-1.0.0\main.py", line 269, in <module>
    num_credentials = len(json.loads(os.getenv('ENV_PLACE_USERNAME')))
  File "C:\Program Files\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)`

My .env file is set up, don't really know why this is happening. I tried reinstall python, setting up the path for dotenv. have no clue why this is happening.

**Comment by rdeepak2002** [comment]
Hey what’s up. Could you post the output of console.log(os.getenv('ENV_PLACE_USERNAME')) before the num_credentials variable is set?

**Comment by rdeepak2002** [comment]
Also you might have to double check that your ‘ and “ quotation marks are correct.

**Comment by NotNer0** [comment]
thanks for telling me to check my quotations! that was the problem, but now I get a new error. I can get to the point of refreshing the access token. after that, this error comes up


Exception in thread Thread-1 (task):
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\reddit-place-script-2022-1.0.0\main.py", line 230, in task
    new_rgb = closest_color(target_rgb, rgb_colors_array)
  File "C:\reddit-place-script-2022-1.0.0\main.py", line 60, in closest_color
    r, g, b = target_rgb
TypeError: cannot unpack non-iterable int object

**Comment by rdeepak2002** [comment]
Np!

Hm that's an odd issue. Is the input image you are providing a jpeg (.jpg) image with no transparency? Also have you pulled the latest version of the code? I would suggest running the code with the image I provided first. Let me know how it goes!

**Comment by NotNer0** [comment]
that was the problem, i didn't want to use photoshop so I kept just using online background removers, but while they removed the background, it makes it into png. i thought just converting .png to .jpg would fix it but it didn't.

guess ill open up photoshop. thank you!
