### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by XanderSo156** [rdeepak2002/reddit-place-script-2022#123]
traceback error

`[02-Apr-22 16:55:12] :: [INFO] - place-script started
Traceback (most recent call last):
  File "C:\Users\xande\Documents\redditplacescript\main.py", line 560, in <module>
    client = PlaceClient()
  File "C:\Users\xande\Documents\redditplacescript\main.py", line 31, in __init__
    self.json_data = self.get_json_data()
  File "C:\Users\xande\Documents\redditplacescript\main.py", line 100, in get_json_data
    json_data = json.load(f)
  File "C:\Users\xande\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\xande\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\xande\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\xande\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 20 column 3 (char 614)`

im on the latest version of the script as of now, 4aeb573

**Comment by rdeepak2002** [comment]
Seems like you might be missing a comma in your config.json file

**Comment by XanderSo156** [comment]
that was it, thanks

**Comment by rdeepak2002** [comment]
No problem.
