### ISSUE TITLE
[BUG] TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by JoshTPro** [rdeepak2002/reddit-place-script-2022#128]
Traceback (most recent call last):
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Coding\reddit-place-script-2022\main.py", line 484, in task
    current_r, current_c, new_rgb = self.get_unset_pixel(
  File "D:\Coding\reddit-place-script-2022\main.py", line 337, in get_unset_pixel
    target_rgb = self.pix[x, y][:3]
`TypeError: 'int' object is not subscriptable`

**Comment by rdeepak2002** [comment]
Hello, do you still get this issue with the latest code? Also try using the default image provided in our repository to see if that works.

**Comment by Plantchant** [comment]
Are you using a 'png'? If so, please try a 'jpg'. Let me know if that fixes it.

**Comment by RomainL972** [comment]
Sometimes the solution is to open the PNG file in MS Paint then save it as a PNG from there.

**Comment by thoroc** [comment]
Should be fixed with https://github.com/rdeepak2002/reddit-place-script-2022/pull/250. Closing for now. Feel free to re-open if you are still encountering the issue.
