### ISSUE TITLE
received response:  {"error": "invalid_grant"} error

### ISSUE THREAD

**Issue by saakethm** [rdeepak2002/reddit-place-script-2022#13]
Thread #0
refreshing access token...
received response:  {"error": "invalid_grant"}
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 208, in task
    access_tokens[credentials_index] = response_data["access_token"]
KeyError: 'access_token'

**Comment by saakethm** [comment]
wrong password
