### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by bebnista** [rdeepak2002/reddit-place-script-2022#131]
[02-Apr-22 23:04:46] :: [INFO] - place-script started
[02-Apr-22 23:04:46] :: [INFO] - Loaded image size: (30, 30)
[02-Apr-22 23:04:47] :: [INFO] - Thread #0 :: 
[02-Apr-22 23:04:47] :: [INFO] - Thread #0 :: Refreshing access token
[02-Apr-22 23:04:47] :: [DEBUG] - Starting new HTTPS connection (1): ssl.reddit.com:443
[02-Apr-22 23:04:48] :: [DEBUG] - https://ssl.reddit.com:443 "POST /api/v1/access_token HTTP/1.1" 200 122
[02-Apr-22 23:04:48] :: [DEBUG] - Received response: {"access_token": "1681658685881-gvGOQgqiTrfs95Iyg43G56Rsuj4pbQ", "token_type": "bearer", "expires_in": 3600, "scope": "*"}
[02-Apr-22 23:04:48] :: [INFO] - Received new access token: 16816************
[02-Apr-22 23:04:48] :: [INFO] - Getting board
[02-Apr-22 23:04:49] :: [DEBUG] - Starting new HTTPS connection (1): hot-potato.reddit.com:443
[02-Apr-22 23:04:49] :: [INFO] - Thread #1 :: 
[02-Apr-22 23:04:49] :: [INFO] - Thread #1 :: Refreshing access token
[02-Apr-22 23:04:49] :: [DEBUG] - Starting new HTTPS connection (1): ssl.reddit.com:443
[02-Apr-22 23:04:49] :: [DEBUG] - https://hot-potato.reddit.com:443 "GET /media/canvas-images/1648933488912-0-f-4cG3XJKn.png HTTP/1.1" 200 190704
[02-Apr-22 23:04:49] :: [INFO] - Received board image: https://hot-potato.reddit.com/media/canvas-images/1648933488912-0-f-4cG3XJKn.png
[02-Apr-22 23:04:49] :: [DEBUG] - STREAM b'IHDR' 16 13
[02-Apr-22 23:04:49] :: [DEBUG] - STREAM b'PLTE' 41 99
[02-Apr-22 23:04:49] :: [DEBUG] - STREAM b'tRNS' 152 1
[02-Apr-22 23:04:49] :: [DEBUG] - STREAM b'IDAT' 165 32768
[02-Apr-22 23:04:49] :: [DEBUG] - 1495, 226
[02-Apr-22 23:04:49] :: [DEBUG] - 0, 113, boardimg, 30, 30
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Pulpit/bot-place/reddit-place-script-2022/main.py", line 432, in task
    current_r, current_c, new_rgb = self.get_unset_pixel(
  File "/root/Pulpit/bot-place/reddit-place-script-2022/main.py", line 287, in get_unset_pixel
    target_rgb = self.pix[x, y][:3]
IndexError: image index out of range
[02-Apr-22 23:04:50] :: [DEBUG] - https://ssl.reddit.com:443 "POST /api/v1/access_token HTTP/1.1" 200 122
[02-Apr-22 23:04:50] :: [DEBUG] - Received response: {"access_token": "1681705706882-GOPVLVzqJ1C8rqOPxedcaw3F3rE3FQ", "token_type": "bearer", "expires_in": 3600, "scope": "*"}
[02-Apr-22 23:04:50] :: [INFO] - Received new access token: 16817************
[02-Apr-22 23:04:50] :: [INFO] - Getting board
[02-Apr-22 23:04:51] :: [DEBUG] - Starting new HTTPS connection (1): hot-potato.reddit.com:443
[02-Apr-22 23:04:51] :: [DEBUG] - https://hot-potato.reddit.com:443 "GET /media/canvas-images/1648933490800-0-f-hrm6VmGx.png HTTP/1.1" 200 190717
[02-Apr-22 23:04:51] :: [INFO] - Received board image: https://hot-potato.reddit.com/media/canvas-images/1648933490800-0-f-hrm6VmGx.png
[02-Apr-22 23:04:51] :: [DEBUG] - STREAM b'IHDR' 16 13
[02-Apr-22 23:04:51] :: [DEBUG] - STREAM b'PLTE' 41 99
[02-Apr-22 23:04:51] :: [DEBUG] - STREAM b'tRNS' 152 1
[02-Apr-22 23:04:51] :: [DEBUG] - STREAM b'IDAT' 165 32768
[02-Apr-22 23:04:51] :: [DEBUG] - 1495, 226
[02-Apr-22 23:04:51] :: [DEBUG] - 0, 113, boardimg, 30, 30
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Pulpit/bot-place/reddit-place-script-2022/main.py", line 432, in task
    current_r, current_c, new_rgb = self.get_unset_pixel(
  File "/root/Pulpit/bot-place/reddit-place-script-2022/main.py", line 287, in get_unset_pixel
    target_rgb = self.pix[x, y][:3]
IndexError: image index out of range

**Comment by ShaunB56** [comment]
Your "start_coords" in config.json is probably not within the pixel ratio of your image.

Remember the "start_coords" (which contains coordinates of within your image) isn't the same as the "image_start_coords" (which contains coordinates relative to the entire board/canvas).

**Comment by bebnista** [comment]
> Your "start_coords" in config.json is probably not within the pixel ratio of your image.
> 
> Remember the "start_coords" (which contains coordinates of within your image) isn't the same as the "image_start_coords" (which contains coordinates relative to the entire board/canvas).

thanks, it worked

**Comment by ShaunB56** [comment]
No problem!

**Comment by rdeepak2002** [comment]
Closing issue since it has been resolved.
