### ISSUE TITLE
[BUG] Exception after loading image

### ISSUE THREAD

**Issue by Balint837** [rdeepak2002/reddit-place-script-2022#137]
I'm getting the error below when trying to run this script:

Exception in thread Thread-1 (task):
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\Desktop\reddit-place-script-2022-main\main.py", line 484, in task
    current_r, current_c, new_rgb = self.get_unset_pixel(
  File "C:\Users\User\Desktop\reddit-place-script-2022-main\main.py", line 337, in get_unset_pixel
    target_rgb = self.pix[x, y][:3]
TypeError: 'int' object is not subscriptable

How do I fix this?

**Comment by Balint837** [comment]
Nvm, converting the img to RGB on line 110 fixes the issue.

**Comment by robiot** [comment]
> Nvm, converting the img to RGB on line 110 fixes the issue.

Yep thats because pngs have rgba instead of rgb because of opacity. This could be fixed from code to check if it is a png. Then convert to rgb

**Comment by rdeepak2002** [comment]
Closing issue since we have added png support.

**Comment by ItCameFr0mMars** [comment]
I still get this #180
