### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Guavabi** [rdeepak2002/reddit-place-script-2022#147]
# Bug Report Form

## Checklist

- [Yes ] I am using the latest version of the code.
- [ Yes] I am absolutely sure I read the README in its entirety.
- [ Yes] I have made sure this is not a duplicate issue.
- [ Yes] I have filled out this form correctly.

## Describe the bug

```
[02-Apr-22 22:51:00] :: [INFO] - place-script started
Traceback (most recent call last):
  File "/usr/src/app/./main.py", line 560, in <module>
    client = PlaceClient()
  File "/usr/src/app/./main.py", line 31, in __init__
    self.json_data = self.get_json_data()
  File "/usr/src/app/./main.py", line 100, in get_json_data
    json_data = json.load(f)
  File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 7 column 30 (char 184)
```

## To Reproduce

Steps to trigger the bug:

1. Go to configure image/workers/secret/get docker downloaded and such
2. go to terminal and paste "docker build . -t place-bot" , wait for that then run "docker run place-bot"

## Expected behavior

should start placing tiles?

## Additional context

i already ran the additional code that was provided if there was JSON decoder error "
{
    "thread_delay": 2,
    "unverified_place_frequency": false,
}
"
and that didnt help

**Comment by rdeepak2002** [comment]
Hello, can you paste your config.json with the confidential strings replaced with a "*"?

Also you might be missing a quotation mark somewhere based off the logs.

**Comment by Guavabi** [comment]
{
    "image_path": "image.jpg",
    "image_start_coords": [135, 660],
    "thread_delay": 1,
    "unverified_place_frequency": "False",
    "workers": { 
        "TheGridBegins8": {
            "password": "****",
            "client_id": "****",
            "client_secret": "******",
            "start_coords": [135, 660]
        },
        "TheGridBegins5": { 
            "password": "****",
            "client_id": "****",
            "client_secret": "******",
            "start_coords": [140, 666]

	"thread_delay": 2,
    "unverified_place_frequency": false,
        }
    }
}

**Comment by rdeepak2002** [comment]
You are missing a comma at the end of "start_coords": [140, 666]".

This is a useful website to check for JSON errors: https://jsonlint.com/

<img width="877" alt="Screen Shot 2022-04-02 at 7 06 14 PM" src="https://user-images.githubusercontent.com/7110480/161404273-c588497f-a43c-4e03-ba00-ff7a690242be.png">

**Comment by Guavabi** [comment]
ok so that did some work on it but im still getting this 


docker run place-bot
[02-Apr-22 23:12:06] :: [INFO] - place-script started
[02-Apr-22 23:12:06] :: [INFO] - Loaded image size: (122, 118)
[02-Apr-22 23:12:07] :: [INFO] - Thread #0 :: 
[02-Apr-22 23:12:07] :: [INFO] - Thread #0 :: Refreshing access token
[02-Apr-22 23:12:08] :: [INFO] - Received new access token: 16811************
[02-Apr-22 23:12:08] :: [INFO] - Getting board
[02-Apr-22 23:12:08] :: [INFO] - Thread #1 :: 
[02-Apr-22 23:12:08] :: [INFO] - Thread #1 :: Refreshing access token
An error occured. Make sure you have the correct credentials. Response data: {'error': 'invalid_grant'}
Got image: 
Exception in thread Thread-1 (task):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/./main.py", line 484, in task
    current_r, current_c, new_rgb = self.get_unset_pixel(
  File "/usr/src/app/./main.py", line 337, in get_unset_pixel
    target_rgb = self.pix[x, y][:3]
IndexError: image index out of range

**Comment by Guavabi** [comment]
I know there are some errors there in the .py files and i can locate them i just dont have the experience with python to fix them

**Comment by ZorudaRinku** [comment]
Make sure you are on latest version. I believe that is an error when all pixels match your target image

**Comment by rdeepak2002** [comment]
Hello, are you still encountering this error with the latest code?

**Comment by Guavabi** [comment]
Nope everything is working fine now thanks!
