### ISSUE TITLE
Am I being rate limited?

### ISSUE THREAD

**Issue by tbrechner** [rdeepak2002/reddit-place-script-2022#171]
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/tbrechner/Downloads/reddit-place-script-2022/main.py", line 443, in task
    response_data = r.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value]
<!doctype html>
<html><head><title>Ow! -- reddit.com</title>
  <script type="text/javascript">
    // send metric to our internal tracker.
    function makeRequest(url, data) {
      var dataString;
      try {
        dataString = JSON.stringify(data);
      } catch (e) {
        return false;
      }
      if (window.XMLHttpRequest) {
        httpRequest = new XMLHttpRequest();
      } else if (window.ActiveXObject) {
        try {
          httpRequest = new ActiveXObject("Msxml2.XMLHTTP");
        }
        catch (e) {
          try {
            httpRequest = new ActiveXObject("Microsoft.XMLHTTP");
          }
          catch (e) {}
        }
      }
      if (!httpRequest) {
        return false;
      }
      httpRequest.open('POST', url);
      httpRequest.setRequestHeader('Content-Type', 'application/json; charset=utf-8');
      httpRequest.send(dataString);
    }
    makeRequest('https://stats.redditmedia.com', {cdnError:{error50x:1,}});
  </script>
<style>
body{text-align:center;position:absolute;top:50%;margin:0;margin-top:-275px;width:100%}
h2,h3{color:#555;font:bold 200%/100px sans-serif;margin:0}
h3{color:#777;font:normal 150% sans-serif}
</style>
</head>
<img src=//redditstatic.s3.amazonaws.com/heavy-load.png alt="">
<h2>Our CDN was unable to reach our servers</h2>
Please check <a href="http://www.redditstatus.com/">www.redditstatus.com</a> if you consistently get this error.
: 1
```

I also put my config.json file into jsonlint.com, and it is valid JSON.

**Comment by jacksors** [comment]
I think the reddit api is down

**Comment by tbrechner** [comment]
Oh, did they state when it would be back up?

**Comment by Ferotiq** [comment]
no, they haven't even reported it on the status yet.

**Comment by rdeepak2002** [comment]
The API is down. You can see this by visiting this page: https://www.reddit.com/prefs/apps

**Comment by Nebula6** [comment]
oh wow so what were unintentionally ddosing old reddit so no bots can work now

**Comment by Risewill23** [comment]
Even verifying accounts is gone
![image](https://user-images.githubusercontent.com/69612616/161406175-8244196d-86bc-409d-9b23-bae0e486c672.png)

**Comment by Nebula6** [comment]
I was using my main account as a bit earlier...![Screenshot_20220403-015109_Reddit.jpg](https://user-images.githubusercontent.com/62147347/161406575-60716848-512d-4c1c-b98c-5ac10dfb069f.jpg)

**Comment by Mte90** [comment]
I got the same error, the bot just crashed in that case, so if the CDN dies again all the bots crashes
