### ISSUE TITLE
[BUG] what does this mean

### ISSUE THREAD

**Issue by Guavabi** [rdeepak2002/reddit-place-script-2022#172]
# Bug Report Form

## Checklist

- [ Yes] I am using the latest version of the code.
- [ Yes] I am absolutely sure I read the README in its entirety.
- [Yes ] I have made sure this is not a duplicate issue.
- [ Yes] I have filled out this form correctly.

## Describe the bug

docker run place-bot
2022-04-03 00:20:31.751 | INFO     | __main__:load_image:114 - Loaded image size: (122, 118)
2022-04-03 00:20:32.756 | INFO     | __main__:task:397 - Thread #0 :: 
2022-04-03 00:20:32.757 | INFO     | __main__:task:412 - Thread #0 :: Refreshing access token
Exception in thread Thread-1 (task):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/./main.py", line 443, in task
    response_data = r.json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] 
<!doctype html>
<html><head><title>Ow! -- reddit.com</title>
  <script type="text/javascript">
    // send metric to our internal tracker.
    function makeRequest(url, data) {
      var dataString;
      try {
        dataString = JSON.stringify(data);
      } catch (e) {
        return false;
      }
      if (window.XMLHttpRequest) {
        httpRequest = new XMLHttpRequest();
      } else if (window.ActiveXObject) {
        try {
          httpRequest = new ActiveXObject("Msxml2.XMLHTTP");
        }
        catch (e) {
          try {
            httpRequest = new ActiveXObject("Microsoft.XMLHTTP");
          }
          catch (e) {}
        }
      }
      if (!httpRequest) {
        return false;
      }
      httpRequest.open('POST', url);
      httpRequest.setRequestHeader('Content-Type', 'application/json; charset=utf-8');
      httpRequest.send(dataString);
    }
    makeRequest('https://stats.redditmedia.com', {cdnError:{error50x:1,}});
  </script>
<style>
body{text-align:center;position:absolute;top:50%;margin:0;margin-top:-275px;width:100%}
h2,h3{color:#555;font:bold 200%/100px sans-serif;margin:0}
h3{color:#777;font:normal 150% sans-serif}
</style>
</head>
<img src=//redditstatic.s3.amazonaws.com/heavy-load.png alt="">
<h2>Our CDN was unable to reach our servers</h2>
Please check <a href="http://www.redditstatus.com/">www.redditstatus.com</a> if you consistently get this error.
: 1
2022-04-03 00:20:33.773 | INFO     | __main__:task:397 - Thread #1 :: 
2022-04-03 00:20:33.774 | INFO     | __main__:task:412 - Thread #1 :: Refreshing access token
Exception in thread Thread-2 (task):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/./main.py", line 443, in task
    response_data = r.json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] 
<!doctype html>
<html><head><title>Ow! -- reddit.com</title>
  <script type="text/javascript">
    // send metric to our internal tracker.
    function makeRequest(url, data) {
      var dataString;
      try {
        dataString = JSON.stringify(data);
      } catch (e) {
        return false;
      }
      if (window.XMLHttpRequest) {
        httpRequest = new XMLHttpRequest();
      } else if (window.ActiveXObject) {
        try {
          httpRequest = new ActiveXObject("Msxml2.XMLHTTP");
        }
        catch (e) {
          try {
            httpRequest = new ActiveXObject("Microsoft.XMLHTTP");
          }
          catch (e) {}
        }
      }
      if (!httpRequest) {
        return false;
      }
      httpRequest.open('POST', url);
      httpRequest.setRequestHeader('Content-Type', 'application/json; charset=utf-8');
      httpRequest.send(dataString);
    }
    makeRequest('https://stats.redditmedia.com', {cdnError:{error50x:1,}});
  </script>
<style>
body{text-align:center;position:absolute;top:50%;margin:0;margin-top:-275px;width:100%}
h2,h3{color:#555;font:bold 200%/100px sans-serif;margin:0}
h3{color:#777;font:normal 150% sans-serif}
</style>
</head>
<img src=//redditstatic.s3.amazonaws.com/heavy-load.png alt="">
<h2>Our CDN was unable to reach our servers</h2>
Please check <a href="http://www.redditstatus.com/">www.redditstatus.com</a> if you consistently get this error.
: 1

## To Reproduce 

Run "docker run place-bot"

place pixels

**Comment by Ferotiq** [comment]
duplicate

**Comment by rdeepak2002** [comment]
The API is down. You can see this by visiting this page: https://www.reddit.com/prefs/apps

<img width="885" alt="Screen Shot 2022-04-02 at 8 27 39 PM" src="https://user-images.githubusercontent.com/7110480/161406049-0a98356a-3ece-4891-94fb-e187667b43a5.png">
