### ISSUE TITLE
[BUG] Json Decoder Error

### ISSUE THREAD

**Issue by AReallyGenericUsername** [rdeepak2002/reddit-place-script-2022#183]
After following the instructions provided on the Readme.md it seems that there might be an issue with the json library? Nothing seems out of the ordinary, I have tried using python both from the windows store and from the official python website.

Error Message:
```C:\Users\[USER]\Downloads\reddit-place-script-2022-main\reddit-place-script-2022-main>python main.py
Traceback (most recent call last):
  File "C:\Users\[USER]\Downloads\reddit-place-script-2022-main\reddit-place-script-2022-main\main.py", line 561, in <module>
    main()
  File "C:\Users\[USER]\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\[USER]\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\[USER]\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\[USER]\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\[USER]\Downloads\reddit-place-script-2022-main\reddit-place-script-2022-main\main.py", line 555, in main
    client = PlaceClient()
  File "C:\Users\[USER]\Downloads\reddit-place-script-2022-main\reddit-place-script-2022-main\main.py", line 28, in __init__
    self.json_data = self.get_json_data()
  File "C:\Users\[USER]\Downloads\reddit-place-script-2022-main\reddit-place-script-2022-main\main.py", line 99, in get_json_data
    json_data = json.load(f)
  File "C:\Users\[USER]\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\[USER]\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\[USER]\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\[USER]\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 10 column 61 (char 332)

json.decoder.JSONDecodeError: Invalid control character at: line 10 column 61 (char 332)
```

config.json file looks like this:
```{
	"image_path": "image.jpg",
	"image_start_coords": [123,456 ],
	"thread_delay": 2,
	"unverified_place_frequency": "False",
	"workers": {
		"worker1username": {
			"password": "L337Passw-0rdW1thSymb0l$andSuch",
			"client_id": "UpPerAndl0Werc4seTh1ngs",
			"client_secret": "Cl1entS3cret!but_with-DashesandSuch",
			"start_coords": [0, 0]
		},
		"worker2username": {
			"password": "L337Passw-0rdW1thSymb0l$andSuch",
			"client_id": "UpPerAndl0Werc4seTh1ngs",
			"client_secret": "UpPerAndl0Werc4seTh1ngs",
			"start_coords": [0, 0]
		}
	}
}
```

**Comment by rdeepak2002** [comment]
Hello, when you paste your contents of config.json into this linter does it pass?: https://jsonlint.com/

Also I see a space in the array:

<img width="106" alt="Screen Shot 2022-04-03 at 1 01 07 AM" src="https://user-images.githubusercontent.com/7110480/161412314-f78f4a75-57e3-45b4-a67b-9da3eca30bd2.png">

**Comment by rdeepak2002** [comment]
Hm actually never mind it seems like the JSON is valid.

<img width="761" alt="Screen Shot 2022-04-03 at 1 01 51 AM" src="https://user-images.githubusercontent.com/7110480/161412345-24e87b82-aa54-4c76-bc40-6e4419ccb790.png">

**Comment by BlazingFire007** [comment]
`"False"` needs to be a boolean value and not a string. Change it to `false`

**Comment by rdeepak2002** [comment]
I pasted in your JSON (and replaced the credentials with mine) and it seems to run:

<img width="1728" alt="Screen Shot 2022-04-03 at 1 06 21 AM" src="https://user-images.githubusercontent.com/7110480/161412475-020a0b64-9611-40c2-8dcb-99e44b007964.png">

**Comment by AReallyGenericUsername** [comment]
There might be an update with the code, I will pull the most recent and run again.

**Comment by AReallyGenericUsername** [comment]
Code does still not work. Would request a solution as although this bug was closed, it seems that other users are have the same issue 

https://github.com/rdeepak2002/reddit-place-script-2022/issues/96#issue-1190717750 
https://github.com/rdeepak2002/reddit-place-script-2022/issues/288

to name a few

Put it through VSCode and got this.
![wwwww](https://user-images.githubusercontent.com/38790532/161445716-56adecad-e3c6-46e7-9bdc-bdb7055314f8.png)

@Risewill23 Could you please re-open this issue? or is there a workaround that I am unaware of...
