### ISSUE TITLE
[BUG] Auto Close CMD

### ISSUE THREAD

**Issue by 16DigitCC** [rdeepak2002/reddit-place-script-2022#197]
I open start.bat or startverbose.bat and cmd open like this and auto close. How to fix this? thankyou
![image](https://user-images.githubusercontent.com/25837207/161416234-5a83bd02-eca1-4c2f-8a82-290a3c6b3cef.png)

**Comment by Risewill23** [comment]
It should be going right to the script when its done

**Comment by 16DigitCC** [comment]
it should be, but after opening start.bat and auto close cmd then nothing happens

> It should be going right to the script when its done

**Comment by Maj-ew** [comment]
Run cmd there and type start.bat in cmd and check if there are any errors.
I am currently getting something like this for some reason and it doesn't work
```
Traceback (most recent call last):
  File "C:\reddit\reddit-place-script-2022-main\main.py", line 621, in <module>
    main()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\reddit\reddit-place-script-2022-main\main.py", line 615, in main
    client = PlaceClient(config_path=config)
  File "C:\reddit\reddit-place-script-2022-main\main.py", line 28, in __init__
    self.json_data = self.get_json_data(config_path)
  File "C:\reddit\reddit-place-script-2022-main\main.py", line 121, in get_json_data
    json_data = json.load(f)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 54 column 1 (char 1010)

C:\reddit\reddit-place-script-2022-main>
```

**Comment by thedankeststorm** [comment]
Don't open the file directly. First open cmd.exe, point to the folder that has the file, then run "start.bat". It should stop closing cmd and show you the error instead.
