### ISSUE TITLE
No Content Found to pass to BeautifulSoup [BUG]

### ISSUE THREAD

**Issue by clutch70** [rdeepak2002/reddit-place-script-2022#200]
# Bug Report Form

## Checklist

- [x ] I am using the latest version of the code.
- [x ] I am absolutely sure I read the README in its entirety.
- [x ] I have made sure this is not a duplicate issue.
- x[ ] I have filled out this form correctly.

## Describe the bug
I was getting the error below

```
PS F:\scripts\reddit-place-script-2022-main_newest\reddit-place-script-2022-main> python3.exe .\main.py --debug
2022-04-03 02:45:18.429 | INFO     | __main__:load_image:140 - Loaded image size: (9, 9)
2022-04-03 02:45:19.433 | INFO     | __main__:task:428 - Thread #0 ::
2022-04-03 02:45:19.434 | INFO     | __main__:task:443 - Thread #0 :: Refreshing access token
Authorization successful!
Obtaining access token...
2022-04-03 02:45:21.232 | INFO     | __main__:task:482 - Client get is <Response [200]>
Exception in thread Thread-1 (task):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "F:\scripts\reddit-place-script-2022-main_newest\reddit-place-script-2022-main\main.py", line 486, in task
    .contents[0][len("window.__r = ") : -1]
AttributeError: 'NoneType' object has no attribute 'contents'

```
and found that after adding a line "logger.info("Client get is {}", r)" at 482 I was getting an HTTP 429, too many requests. I added a few other lines from some other folks and now get an HTTP 200 but still the same traceback.

Replace this text with a description of the bug.

## To Reproduce

Steps to trigger the bug:

Run main.py with the config below
Authorization successful...
Obtaining access token...
200 HTTP, then traceback

```
{
    "image_path": "image.png",
    "image_start_coords": [1, 1],
    "thread_delay": 2,
    "unverified_place_frequency": false,
    "workers": {
        "username": {
            "password": "pw",
            "client_id": "id",
            "client_secret": "secret",
            "start_coords": [1, 1]
        }
    }
}
```

**Comment by Plantchant** [comment]
New commit has BS4 removed. Not sure who put it there.

**Comment by thoroc** [comment]
Reddit seems to have gotten wiser to the script. I can confirm I am seeing 429: Too many request as a response code on the same line

**Comment by thoroc** [comment]
Similar to #212
