### ISSUE TITLE
[BUG] 'Logger' object has no attribute 'fatal'

### ISSUE THREAD

**Issue by RomainL972** [rdeepak2002/reddit-place-script-2022#232]
# Bug Report Form

## Checklist

- [X] I am using the latest version of the code.
- [X] I am absolutely sure I read the README in its entirety.
- [X] I have made sure this is not a duplicate issue.
- [X] I have filled out this form correctly.

## Describe the bug

When a fatal error occurs while opening the image, logger.fatal is called, which doesn't exist. It should be replaced by something else.

## To Reproduce

Steps to trigger the bug:

1. Remove image.jpg
2. Create config.json from sample
3. Run the script

## Expected behavior

The program should have ended with an error message for the user.

## Additional context

```
Traceback (most recent call last):
  File "./main.py", line 662, in <module>
    main()
  File "/home/romain/dev/reddit-fork/env/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/romain/dev/reddit-fork/env/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/romain/dev/reddit-fork/env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/romain/dev/reddit-fork/env/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "./main.py", line 656, in main
    client = PlaceClient(config_path=config)
  File "./main.py", line 75, in __init__
    self.load_image()
  File "./main.py", line 141, in load_image
    logger.fatal("Failed to load image")
AttributeError: 'Logger' object has no attribute 'fatal'
```

**Comment by robiot** [comment]
Yeah this is probably something that has been left over from the old logging library

**Comment by thoroc** [comment]
Should be fixed. Thank you
