### ISSUE TITLE
[BUG] crashes with jpg

### ISSUE THREAD

**Issue by funwithtriangles** [rdeepak2002/reddit-place-script-2022#237]
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [x] I have made sure this is not a duplicate issue.
- [x] I have filled out this form correctly.

## Describe the bug

```
  File "/Users/alex/Sites/reddit-place-script-2022/main.py", line 586, in task
    current_r, current_c, new_rgb = self.get_unset_pixel(
  File "/Users/alex/Sites/reddit-place-script-2022/main.py", line 405, in get_unset_pixel
    new_rgb = self.closest_color(target_rgb)
  File "/Users/alex/Sites/reddit-place-script-2022/main.py", line 106, in closest_color
    if target_rgb[3] != 0:
IndexError: tuple index out of range
```

## To Reproduce

Use a jpeg as your target image

This is happening since the transparency PR. `target_rgb` is missing a 4th item when using jpg
https://github.com/rdeepak2002/reddit-place-script-2022/pull/211

**Comment by marnick-s** [comment]
I get this error with a PNG too

**Comment by StoneMcYT** [comment]
Same issue with the image.jpg provided

**Comment by Adenser** [comment]
If 69,42,0 color is presented in the image in first line of code, it will casue this error to be presented in PNGs

For PNGs, transparent layer is supported as transparent (I believe).

**Comment by StoneMcYT** [comment]
Im just going to add the error i got when i used the image.jpg provided 
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/server/reddit-place-script-2022/main.py", line 586, in task
    current_r, current_c, new_rgb = self.get_unset_pixel(
  File "/home/server/reddit-place-script-2022/main.py", line 405, in get_unset_pixel
    new_rgb = self.closest_color(target_rgb)
  File "/home/server/reddit-place-script-2022/main.py", line 106, in closest_color
    if target_rgb[3] != 0:
IndexError: tuple index out of range

```

**Comment by ixi2101** [comment]
Earlier version that at least works with jpeg

`git checkout 3cbaf3fe8c949d49face01292fad1202d3fd4de2`

**Comment by AlexX1-dev** [comment]
Any fix for that?
