### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by chipqs** [rdeepak2002/reddit-place-script-2022#24]
The script was working well before i updated it to the new fork, now im getting an error.

```0 seconds until next pixel is drawn
Getting board
Got image: https://hot-potato.reddit.com/media/canvas-images/1648879576430-0-f-jKSA6UA5.png
22 644
1 0 boardimg 48 35
Exception in thread Thread-1 (task):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ilank\OneDrive\Desktop\pythonProject\main.py", line 345, in task
    current_r, current_c, new_rgb = get_unset_pixel(get_board(access_tokens[credentials_index]), current_r,
  File "C:\Users\ilank\OneDrive\Desktop\pythonProject\main.py", line 178, in get_unset_pixel
    new_rgb = closest_color(target_rgb, rgb_colors_array)
  File "C:\Users\ilank\OneDrive\Desktop\pythonProject\main.py", line 62, in closest_color
    r, g, b = target_rgb
TypeError: cannot unpack non-iterable int object```

**Comment by chipqs** [comment]
Even happens with one thread.

**Comment by DeltaNeverUsed** [comment]
png's are not supported

**Comment by chipqs** [comment]
thats not the issue but nvm. make sure to download to new folder instead of just replacing files.

**Comment by DeltaNeverUsed** [comment]
oop, my mistake sorry i miss read

**Comment by JAKONL** [comment]
@chipqs - so you have this sorted? I'd like to close this if so.
