### ISSUE TITLE
"Exception in thread Thread" error on latest version [BUG] 

### ISSUE THREAD

**Issue by markpaul099** [rdeepak2002/reddit-place-script-2022#245]
- [✅] I am using the latest version of the code.
- [✅] I am absolutely sure I read the README in its entirety.
- [✅] I have made sure this is not a duplicate issue.
- [✅] I have filled out this form correctly.

After cloning the latest version on my raspberry pi this error showed up, The version I used like 4 hours ago on pc worked perfectly, I also tried the latest version on pc and got the same error

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/reddit-place-script-2022/main.py", line 586, in task
    current_r, current_c, new_rgb = self.get_unset_pixel(
  File "/home/pi/reddit-place-script-2022/main.py", line 405, in get_unset_pixel
    new_rgb = self.closest_color(target_rgb)
  File "/home/pi/reddit-place-script-2022/main.py", line 106, in closest_color
    if target_rgb[3] != 0:
IndexError: tuple index out of range
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/reddit-place-script-2022/main.py", line 586, in task
    current_r, current_c, new_rgb = self.get_unset_pixel(
  File "/home/pi/reddit-place-script-2022/main.py", line 405, in get_unset_pixel
    new_rgb = self.closest_color(target_rgb)
  File "/home/pi/reddit-place-script-2022/main.py", line 106, in closest_color
    if target_rgb[3] != 0:
IndexError: tuple index out of range
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/reddit-place-script-2022/main.py", line 586, in task
    current_r, current_c, new_rgb = self.get_unset_pixel(
  File "/home/pi/reddit-place-script-2022/main.py", line 405, in get_unset_pixel
    new_rgb = self.closest_color(target_rgb)
  File "/home/pi/reddit-place-script-2022/main.py", line 106, in closest_color
    if target_rgb[3] != 0:
IndexError: tuple index out of range
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/reddit-place-script-2022/main.py", line 586, in task
    current_r, current_c, new_rgb = self.get_unset_pixel(
  File "/home/pi/reddit-place-script-2022/main.py", line 405, in get_unset_pixel
    new_rgb = self.closest_color(target_rgb)
  File "/home/pi/reddit-place-script-2022/main.py", line 106, in closest_color
    if target_rgb[3] != 0:
IndexError: tuple index out of range

**Comment by ixi2101** [comment]
#237

**Comment by Yolwoocle** [comment]
Can confirm.

**Comment by ixi2101** [comment]
Please checkout an earlier version:

git checkout 3cbaf3fe8c949d49face01292fad1202d3fd4de2
