### ISSUE TITLE
[BUG] Tuple index out of range

### ISSUE THREAD

**Issue by NoamikoT** [rdeepak2002/reddit-place-script-2022#247]
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [x] I have made sure this is not a duplicate issue.
- [x] I have filled out this form correctly.

## Describe the bug

Tuple index out of range

## To Reproduce

Steps to trigger the bug:

1. Run "main.py"
2. wait

## Expected behavior

Pixel placed.

## Additional context

Run:
C:\AllInOne\PortableApps\Python374\python.exe G:/Noam/PycharmProjects/Place/main.py
2022-04-03 16:05:52.904 | INFO     | __main__:load_image:148 - Loaded image size: (48, 35)
Authorization successful!
Obtaining access token...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\AllInOne\PortableApps\Python374\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\AllInOne\PortableApps\Python374\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "G:/Noam/PycharmProjects/Place/main.py", line 592, in task
    index,
  File "G:/Noam/PycharmProjects/Place/main.py", line 408, in get_unset_pixel
    new_rgb = self.closest_color(target_rgb)
  File "G:/Noam/PycharmProjects/Place/main.py", line 106, in closest_color
    if target_rgb[3] != 0:
IndexError: tuple index out of range

Process finished with exit code 0

**Comment by nin0-dev** [comment]
Use a PNG image, Solved the problem for me!

**Comment by NoamikoT** [comment]
> Use a PNG image, Solved the problem for me!

I am.

**Comment by markpaul099** [comment]
#245

**Comment by ixi2101** [comment]
Should be fixed on latest
