### ISSUE TITLE
[BUG] missing 1 required positional argument: 'rgb_colors_array' crash

### ISSUE THREAD

**Issue by AlexX1-dev** [rdeepak2002/reddit-place-script-2022#258]
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [x] I have made sure this is not a duplicate issue.
- [x] I have filled out this form correctly.

## Describe the bug

When I try to use the png I have and launch the bots it returns this error in the console
Exception in thread Thread-30 (task):
Traceback (most recent call last):
  File "C:\Users\Alex_X1\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Alex_X1\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Alex_X1\Desktop\reddit-place-script-2022-main\reddit-place-script-2022-main\main.py", line 572, in task
    current_r, current_c, new_rgb = self.get_unset_pixel(
  File "C:\Users\Alex_X1\Desktop\reddit-place-script-2022-main\reddit-place-script-2022-main\main.py", line 385, in get_unset_pixel
    new_rgb = ColorMapper.closest_color(target_rgb)
TypeError: ColorMapper.closest_color() missing 1 required positional argument: 'rgb_colors_array'
## To Reproduce

Steps to trigger the bug:

1. Download the image: https://cdn.discordapp.com/attachments/959799297405227008/960162001030639646/combined.png
2. Enter it as image in the config
3. Run the start.bat

## Expected behavior

The bots should paint the image

## Additional context

The Transparency fix didn't help

**Comment by StoneMcYT** [comment]
Having the same issue
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/server/reddit-place-script-2022/main.py", line 572, in task
    current_r, current_c, new_rgb = self.get_unset_pixel(
  File "/home/server/reddit-place-script-2022/main.py", line 385, in get_unset_pixel
    new_rgb = ColorMapper.closest_color(target_rgb)
TypeError: closest_color() missing 1 required positional argument: 'rgb_colors_array'
```

**Comment by bestgio** [comment]
Getting the same issue over here as well, I wonder if it might have to do with our image size? I'm trying to do a small 13x13 png

**Comment by StoneMcYT** [comment]
> Getting the same issue over here as well, I wonder if it might have to do with our image size? I'm trying to do a small 13x13 png

I was testing with the image provided (image.jpg)

**Comment by ixi2101** [comment]
#262  Will fix this

**Comment by bestgio** [comment]
> 

I just tried testing out the provided image as well, crashes on my end too

**Comment by AlexX1-dev** [comment]
> 

You are a lifesaver mate, let's hope it gets merged soon.

**Comment by StoneMcYT** [comment]
> #262 Will fix this
I just tested your fork it dosnt seam to
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/server/reddit-place-script-2022/main.py", line 572, in task
    current_r, current_c, new_rgb = self.get_unset_pixel(
  File "/home/server/reddit-place-script-2022/main.py", line 385, in get_unset_pixel
    new_rgb = ColorMapper.closest_color(target_rgb)
TypeError: closest_color() missing 1 required positional argument: 'rgb_colors_array'
```

**Comment by StoneMcYT** [comment]
> > #262 Will fix this
> > I just tested your fork it dosnt seam to
> 
> ```
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.9/threading.py", line 910, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/server/reddit-place-script-2022/main.py", line 572, in task
>     current_r, current_c, new_rgb = self.get_unset_pixel(
>   File "/home/server/reddit-place-script-2022/main.py", line 385, in get_unset_pixel
>     new_rgb = ColorMapper.closest_color(target_rgb)
> TypeError: closest_color() missing 1 required positional argument: 'rgb_colors_array'
> ```
> 
> **Wait i cloned the wrong branch im gonna retest **

Back from testing i am happy to confirm it DOES work
