### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Whiskey-Bravo** [rdeepak2002/reddit-place-script-2022#259]
# Bug Report Form

## Checklist

- [Yes] I am using the latest version of the code.
- [Yes] I am absolutely sure I read the README in its entirety.
- [Yes] I have made sure this is not a duplicate issue.
- [Yes] I have filled out this form correctly.

## Describe the bug

Whenever i try to use a proxy the bot returns an error.
This is what get:

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\pstro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\pstro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "C:\Users\pstro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\urllib3\connection.py", line 369, in connect
    self._tunnel()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 926, in _tunnel
    (version, code, message) = response._read_status()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response`

## To Reproduce

Steps to trigger the bug:

1. I go to the config file and add the proxy like the readme describes with valid socks proxies
2. I save it and start the bot
3. See error

## Expected behavior

Bot should run with proxy enabled

**Comment by Risewill23** [comment]
can you send the config? (User info like passwords replaced with ***)

**Comment by Whiskey-Bravo** [comment]
> can you send the config? (User info like passwords replaced with ***)

{

  "image_path": "image.jpg",
  "image_start_coords": [ 1949, 18 ],
  "thread_delay": 20,
  "unverified_place_frequency": false,
  "proxies": [ "31.130.89.218:1080", "62.112.194.224:1080" ],
  "compact_logging": true,
  "workers": {
    "*****": {
      "password": "******",
      "start_coords": [ 0, 0 ]
    },
    "****": {
      "password": "*****",
      "start_coords": [ 5, 0 ]
    },
    "****": {
      "password": "****",
      "start_coords": [ 0, 1 ]
    },
    "****": {
      "password": "****",
      "start_coords": [ 5, 1 ]
    }
  }
}
