### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jeffro256** [rdeepak2002/reddit-place-script-2022#272]
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [x] I have made sure this is not a duplicate issue.
- [x] I have filled out this form correctly.

## Describe the bug

On startup, authentication is successful, but I get the following error message:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 545, in task
    BeautifulSoup(r.content, features="html.parser")
AttributeError: 'NoneType' object has no attribute 'contents'
```

## To Reproduce

Steps to trigger the bug:
* Run the code

## Expected behavior

To start up with error and place tiles

## Additional context

I'm using reddit old, don't know if that has anything to do with it

**Comment by Risewill23** [comment]
it looks like the code didn't have time to get the website request in time so it looks like its a slow network issue

**Comment by JarradTait** [comment]
It never succeeds and my old code works every time

**Comment by Skyline-9** [comment]
Try running this with the updated script. Are you still running into this issue?
