### ISSUE TITLE
[BUG] json decoder error 

### ISSUE THREAD

**Issue by kiadxn** [rdeepak2002/reddit-place-script-2022#288]
# Bug Report Form

## Checklist

- [ ] I am using the latest version of the code.
- [ ] I am absolutely sure I read the README in its entirety.
- [ ] I have made sure this is not a duplicate issue.
- [ ] I have filled out this form correctly.

## Describe the bug

When I first ran the start.bat everything went fine. now every time i run start.bat in cmd i get an error, even after switching accounts i still get the following error: 

Traceback (most recent call last):
  File "C:\Users\trish\Desktop\reddit-place-script-2022-main\main.py", line 673, in <module>
    main()
  File "C:\Users\trish\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\trish\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\trish\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\trish\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\trish\Desktop\reddit-place-script-2022-main\main.py", line 667, in main
    client = PlaceClient(config_path=config)
  File "C:\Users\trish\Desktop\reddit-place-script-2022-main\main.py", line 27, in __init__
    self.json_data = self.get_json_data(config_path)
  File "C:\Users\trish\Desktop\reddit-place-script-2022-main\main.py", line 100, in get_json_data
    json_data = json.load(f)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 2 column 8 (char 9)

## To Reproduce

Steps to trigger the bug:

1. select path in cmd
2. run start.bat
3. See error

**Comment by Risewill23** [comment]
send your json with the passwords and changed to ***

**Comment by kiadxn** [comment]
> send your json with the passwords and changed to ***

{
    "C:\Games\Image": "pxArt.png",
    "image_start_coords": [728, 710],
    "thread_delay": 2,
    "unverified_place_frequency": false,
    "compact_logging": true,
    "workers": {
        "***": {
            "password": "***",
            "start_coords": [0, 0]
        },
        "***": {
            "password": "***",
            "start_coords": [0, 0]
        }
    }
}

**Comment by kiadxn** [comment]
reinstalling the folder then redoing everything seemed to work but now I'm faced with a web socket error

**Comment by rdeepak2002** [comment]
Yeah there seems to be an issue with our web socket connection: https://github.com/rdeepak2002/reddit-place-script-2022/issues/280

Closing this issue since it has been resolved.
