### ISSUE TITLE
[BUG] after downloading the new update i am faced with a json decoder error every time I run start.bat

### ISSUE THREAD

**Issue by kiadxn** [rdeepak2002/reddit-place-script-2022#293]
# Bug Report Form

## Checklist

- [ ] I am using the latest version of the code.
- [ ] I am absolutely sure I read the README in its entirety.
- [ ] I have made sure this is not a duplicate issue.
- [ ] I have filled out this form correctly.

## Describe the bug

as the title says after downloading the new update I'm faced with json decoder errors. i have tried redownloading the file multiple times to no avail. 

Error:

Traceback (most recent call last):
  File "D:\reddit-place-script-2022-main\main.py", line 683, in <module>
    main()
  File "C:\Users\trish\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\trish\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\trish\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\trish\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\reddit-place-script-2022-main\main.py", line 677, in main
    client = PlaceClient(config_path=config)
  File "D:\reddit-place-script-2022-main\main.py", line 27, in __init__
    self.json_data = self.get_json_data(config_path)
  File "D:\reddit-place-script-2022-main\main.py", line 111, in get_json_data
    json_data = json.load(f)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 2 column 8 (char 9)

D:\reddit-place-script-2022-main>start.bat
Requirement already satisfied: certifi==2021.10.8 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 1)) (2021.10.8)
Requirement already satisfied: charset-normalizer==2.0.12 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 2)) (2.0.12)
Requirement already satisfied: idna==3.3 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 3)) (3.3)
Requirement already satisfied: python-dotenv==0.20.0 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 4)) (0.20.0)
Requirement already satisfied: requests==2.27.1 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 5)) (2.27.1)
Requirement already satisfied: urllib3==1.26.9 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 6)) (1.26.9)
Requirement already satisfied: Pillow~=9.1.0 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 7)) (9.1.0)
Requirement already satisfied: websocket-client~=1.3.2 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 8)) (1.3.2)
Requirement already satisfied: click==8.1.2 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 9)) (8.1.2)
Requirement already satisfied: loguru==0.6.0 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 10)) (0.6.0)
Requirement already satisfied: beautifulsoup4~=4.10.0 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 11)) (4.10.0)
Requirement already satisfied: colorama in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from click==8.1.2->-r requirements.txt (line 9)) (0.4.4)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from loguru==0.6.0->-r requirements.txt (line 10)) (1.1.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from beautifulsoup4~=4.10.0->-r requirements.txt (line 11)) (2.3.1)
WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
You should consider upgrading via the 'C:\Users\trish\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "D:\reddit-place-script-2022-main\main.py", line 683, in <module>
    main()
  File "C:\Users\trish\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\trish\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\trish\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\trish\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\reddit-place-script-2022-main\main.py", line 677, in main
    client = PlaceClient(config_path=config)
  File "D:\reddit-place-script-2022-main\main.py", line 27, in __init__
    self.json_data = self.get_json_data(config_path)
  File "D:\reddit-place-script-2022-main\main.py", line 111, in get_json_data
    json_data = json.load(f)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 2 column 8 (char 9)

D:\reddit-place-script-2022-main>start.bat
Requirement already satisfied: certifi==2021.10.8 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 1)) (2021.10.8)
Requirement already satisfied: charset-normalizer==2.0.12 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 2)) (2.0.12)
Requirement already satisfied: idna==3.3 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 3)) (3.3)
Requirement already satisfied: python-dotenv==0.20.0 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 4)) (0.20.0)
Requirement already satisfied: requests==2.27.1 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 5)) (2.27.1)
Requirement already satisfied: urllib3==1.26.9 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 6)) (1.26.9)
Requirement already satisfied: Pillow~=9.1.0 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 7)) (9.1.0)
Requirement already satisfied: websocket-client~=1.3.2 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 8)) (1.3.2)
Requirement already satisfied: click==8.1.2 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 9)) (8.1.2)
Requirement already satisfied: loguru==0.6.0 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 10)) (0.6.0)
Requirement already satisfied: beautifulsoup4~=4.10.0 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 11)) (4.10.0)
Requirement already satisfied: colorama in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from click==8.1.2->-r requirements.txt (line 9)) (0.4.4)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from loguru==0.6.0->-r requirements.txt (line 10)) (1.1.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\trish\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from beautifulsoup4~=4.10.0->-r requirements.txt (line 11)) (2.3.1)
WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
You should consider upgrading via the 'C:\Users\trish\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "D:\reddit-place-script-2022-main\main.py", line 683, in <module>
    main()
  File "C:\Users\trish\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\trish\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\trish\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\trish\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\reddit-place-script-2022-main\main.py", line 677, in main
    client = PlaceClient(config_path=config)
  File "D:\reddit-place-script-2022-main\main.py", line 27, in __init__
    self.json_data = self.get_json_data(config_path)
  File "D:\reddit-place-script-2022-main\main.py", line 111, in get_json_data
    json_data = json.load(f)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 2 column 8 (char 9)

****

## To Reproduce

Steps to trigger the bug:

1. select path
2. run start.bat
3. See error

**Comment by Risewill23** [comment]
can you send the config

**Comment by kiadxn** [comment]
> can you send the config (Password replaced with ******)

{
    "C:\Games\Image": "pxArt.png",
    "image_start_coords": [25, 0],
    "thread_delay": 2,
    "unverified_place_frequency": false,
    "compact_logging": true,
    "workers": {
        "******": {
            "password": " ******",
            "start_coords": [724, 727]
        },
        "******": {
            "password": " ******",
            "start_coords": [724, 727]
        }
    }
}

**Comment by Risewill23** [comment]
`"C:\Games\Image": "pxArt.png",` should be `"image_path": "C:\Games\Image\pxArt.png",`

**Comment by kiadxn** [comment]
> `"C:\Games\Image": "pxArt.png",` should be `"image_path": "C:\Games\Image\pxArt.png",`

thankyou
