### ISSUE TITLE
KeyError: extensions

### ISSUE THREAD

**Issue by thedankeststorm** [rdeepak2002/reddit-place-script-2022#306]
`Exception in thread Thread-1:                                                                                           Traceback (most recent call last):                                                                                        File "C:\Users\Casey\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner              self.run()                                                                                                            File "C:\Users\Casey\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run                           self._target(*self._args, **self._kwargs)                                                                             File "C:\Users\Casey\Desktop\reddit-place-script-2022-main\main.py", line 710, in task                                    next_pixel_placement_time = self.set_pixel_and_check_ratelimit(                                                       File "C:\Users\Casey\Desktop\reddit-place-script-2022-main\main.py", line 269, in set_pixel_and_check_ratelimit           response.json()["errors"][0]["extensions"]["nextAvailablePixelTs"]                                                  KeyError: 'extensions' `
Not sure if this is only happening to me. It authorized and logged in successfully, but when it starts placing pixels, this happens. I haven't updated the config file to the latest one yet ( with Tor settings )

**Comment by skye5000** [comment]
also happens to me

**Comment by Enyrox** [comment]
same for me

**Comment by Covkie** [comment]
same

**Comment by ixi2101** [comment]
This is the same issue as #299 I think
![image](https://user-images.githubusercontent.com/77992676/161445515-5a950855-8a64-412c-a026-9362eb987ccd.png)

**Comment by skye5000** [comment]
any ideas what might be causing it?

**Comment by mmenzyns** [comment]
> This is the same issue as #299 I think ![image](https://user-images.githubusercontent.com/77992676/161445515-5a950855-8a64-412c-a026-9362eb987ccd.png)

It is indeed same for me. I am getting in response message "'Y' has to be within 0-999 range" with KeyError: extensions exception.

**Comment by omar2205** [comment]
Are you trying place in the new canvas?

**Comment by olbrichj** [comment]
Same here and yes it's in the new canvas

**Comment by skye5000** [comment]
yes

**Comment by thedankeststorm** [comment]
> Are you trying place in the new canvas?

Yes

**Comment by omar2205** [comment]
it needs to be updated to account for the new space

**Comment by rowei99** [comment]
I have this issue as well

**Comment by skye5000** [comment]
![image](https://user-images.githubusercontent.com/54551194/161445653-65e14a2a-a710-46d0-b78a-b612482856b9.png)
heres my error, its slightly different from #299

**Comment by mmenzyns** [comment]
> ![image](https://user-images.githubusercontent.com/54551194/161445653-65e14a2a-a710-46d0-b78a-b612482856b9.png) heres my error, its slightly different from #299

no it's completely same

**Comment by skye5000** [comment]
i dont get the Y has to be between 0-999 message though

**Comment by skye5000** [comment]
oh wait is it because im not running with the debug flag? oops

**Comment by omar2205** [comment]
> i dont get the Y has to be between 0-999 message though

wait for the new canvas update

**Comment by Risewill23** [comment]
its because of the expanded canvas area not working correctly so just use the first area for now

**Comment by Dulappy** [comment]
I have the same issue in the first area as well.

**Comment by CAS-14** [comment]
I hope this gets fixed soon!

**Comment by CosmicHazel** [comment]
Same

**Comment by erolm-a** [comment]
There are currently 2 PRs to solve this: #316 or #317 . The maintainer needs to merge either.

**Comment by memtest2** [comment]
I still get this, is there something I can do to fix this?
