### ISSUE TITLE
Bug: KeyError: '#452A00'

### ISSUE THREAD

**Issue by DeveloperTK** [rdeepak2002/reddit-place-script-2022#307]
I've got this exception
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/christianschliz/Development/scripts/placebot3/reddit-place-script-2022/main.py", line 696, in task
    pixel_color_index = ColorMapper.COLOR_MAP[new_rgb_hex]
KeyError: '#452A00'
```

**Comment by Arvfitii** [comment]
Just had this, figured out that its the hex for RGB 69,42,0, i changed the transparent colors in my image to that color and everything works now

**Comment by Arvfitii** [comment]
> Just had this, figured out that its the hex for RGB 69,42,0, i changed the transparent colors in my image to that color and everything works now

(**the script treats pixels of that color as transparent)

**Comment by ixi2101** [comment]
I was wondering where that hex was coming from

**Comment by end-me-please** [comment]
> Just had this, figured out that its the hex for RGB 69,42,0, i changed the transparent colors in my image to that color and everything works now

how did you do that

**Comment by rdeepak2002** [comment]
I would use an image editing tool like Gimp (https://www.gimp.org/) to place the png image onto a fully colored rectangle with the color (69,42,0). Then export it as a jpg to be extra safe.

**Comment by deemfox** [comment]
i believe this was fixed in #319. transparent png images should now work without any modifications
