### ISSUE TITLE
HELP ME: When I execute start.bat doest'n work

### ISSUE THREAD

**Issue by Trollmo** [rdeepak2002/reddit-place-script-2022#321]
When I execute start.bat doestn work

**Comment by ixi2101** [comment]
What does it say?

**Comment by rdeepak2002** [comment]
Hello, please ensure you have Python installed and added to your Windows path (https://www.python.org/downloads/). 

Also please execute the following code and paste the logs here (make sure to remove any confidential information):

```bash
pip install -r requirements.txt
python main.py --debug
```

**Comment by Trollmo** [comment]
> Hello, please ensure you have Python installed and added to your Windows path (https://www.python.org/downloads/).
> 
> Also please execute the following code and paste the logs here (make sure to remove any confidential information):
> 
> ```shell
> pip install -r requirements.txt
> python main.py --debug
> ```

Ik this is a newbie question but I dont know how to do pip install :/ I dont know how to open python's command line shell

**Comment by bjb28** [comment]
This might help with [installing pip](https://www.geeksforgeeks.org/how-to-install-pip-on-windows/#:~:text=Download%20and%20Install%20pip%3A&text=Download%20the%20get%2Dpip.py,where%20the%20above%20file%20exists.&text=and%20wait%20through%20the%20installation,now%20installed%20on%20your%20system.).  You will likley need to do some googling to find the exact match for your OS.

**Comment by rdeepak2002** [comment]
Hello, if Python is installed to your path you can use any command line application (like the terminal or powershell) to navigate to the project folder, then run the 2 Python commands listed above. 

I haven't used Windows in a long time, but the "cd" command in the terminal will allow you to go into a specific folder and the "dir" command will show you the list of folders in the current directory you are in.

**Comment by Trollmo** [comment]
> Hello, please ensure you have Python installed and added to your Windows path (https://www.python.org/downloads/).
> 
> Also please execute the following code and paste the logs here (make sure to remove any confidential information):
> 
> ```shell
> pip install -r requirements.txt
> python main.py --debug
> ```

![image](https://user-images.githubusercontent.com/71456058/161449244-669e876e-196c-46f1-ab77-0327215bd885.png)
Is this ok?

**Comment by Trollmo** [comment]
Okay, done, now this happends when executing the start
Exception in thread Thread-1 (task):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\olmor\Downloads\reddit-place-script-2022-main\reddit-place-script-2022-main\main.py", line 710, in task
    next_pixel_placement_time = self.set_pixel_and_check_ratelimit(
  File "C:\Users\olmor\Downloads\reddit-place-script-2022-main\reddit-place-script-2022-main\main.py", line 269, in set_pixel_and_check_ratelimit
    response.json()["errors"][0]["extensions"]["nextAvailablePixelTs"]
KeyError: 'extensions'
Exception in thread Thread-3 (task):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\olmor\Downloads\reddit-place-script-2022-main\reddit-place-script-2022-main\main.py", line 710, in task
    next_pixel_placement_time = self.set_pixel_and_check_ratelimit(
  File "C:\Users\olmor\Downloads\reddit-place-script-2022-main\reddit-place-script-2022-main\main.py", line 269, in set_pixel_and_check_ratelimit
    response.json()["errors"][0]["extensions"]["nextAvailablePixelTs"]
KeyError: 'extensions'
Exception in thread Thread-6 (task):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\olmor\Downloads\reddit-place-script-2022-main\reddit-place-script-2022-main\main.py", line 710, in task
    next_pixel_placement_time = self.set_pixel_and_check_ratelimit(
  File "C:\Users\olmor\Downloads\reddit-place-script-2022-main\reddit-place-script-2022-main\main.py", line 269, in set_pixel_and_check_ratelimit
    response.json()["errors"][0]["extensions"]["nextAvailablePixelTs"]
KeyError: 'extensions'
