### ISSUE TITLE
Cannot get Docker container to run

### ISSUE THREAD

**Issue by joshandersn** [rdeepak2002/reddit-place-script-2022#328]
I everything setup and already fixed an issue with "installing pip"

I ran
`docker run place-bot`

and got
`Traceback (most recent call last):
  File "/usr/src/app/./main.py", line 772, in <module>
    main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/app/./main.py", line 766, in main
    client = PlaceClient(config_path=config)
  File "/usr/src/app/./main.py", line 32, in __init__
    self.json_data = self.get_json_data(config_path)
  File "/usr/src/app/./main.py", line 189, in get_json_data
    json_data = json.load(f)
  File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 5 (char 6)`

Any idea on whats going on i've checked the other issues and am stumped right now

Note: running on a M1 mac mini

**Comment by ixi2101** [comment]
It looks like your config.json is incorrect. You will have to rebuild the container on config changes

**Comment by joshandersn** [comment]
> It looks like your config.json is incorrect. You will have to rebuild the container on config changes

Okay ill try that thanks

**Comment by nated0g** [comment]
> It looks like your config.json is incorrect. You will have to rebuild the container on config changes

Or just use a volume so you don't need to rebuild

**Comment by joshandersn** [comment]
> It looks like your config.json is incorrect. You will have to rebuild the container on config changes

Its working thanks a ton!

Now the docker container is having trouble staying on
`2022-04-03 21:27:39.315 | INFO     | __main__:load_image:210 - Converted to rgba

2022-04-03 21:27:39.315 | INFO     | __main__:load_image:213 - Loaded image size: (32, 11)

2022-04-03 21:27:41.248 | SUCCESS  | __main__:task:641 - Authorization successful!

2022-04-03 21:27:41.249 | INFO     | __main__:task:642 - Obtaining access token...

2022-04-03 21:27:43.045 | ERROR    | __main__:task:638 - Authorization failed!

NoneType: None

2022-04-03 21:27:46.911 | INFO     | __main__:task:700 - 

Account Placing: 

2022-04-03 21:27:46.911 | INFO     | __main__:set_pixel_and_check_ratelimit:223 - Thread #0 : Attempting to place Brown (25) pixel at 405, 1288

2022-04-03 21:27:47.328 | ERROR    | __main__:set_pixel_and_check_ratelimit:271 - Thread #0 : Failed placing pixel: rate limited

2022-04-03 21:32:15.901 | INFO     | __main__:task:700 - 

Account Placing: 

2022-04-03 21:32:15.901 | INFO     | __main__:set_pixel_and_check_ratelimit:223 - Thread #0 : Attempting to place Brown (25) pixel at 406, 1288

Exception in thread Thread-1 (task):

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner

    self.run()

  File "/usr/local/lib/python3.10/threading.py", line 946, in run

    self._target(*self._args, **self._kwargs)

  File "/usr/src/app/./main.py", line 712, in task

    next_pixel_placement_time = self.set_pixel_and_check_ratelimit(

  File "/usr/src/app/./main.py", line 269, in set_pixel_and_check_ratelimit

    response.json()["errors"][0]["extensions"]["nextAvailablePixelTs"]

KeyError: 'extensions'`

It cant place a single pixel i guess im getting rateblocked or something i should have foreseen this lol

**Comment by thoroc** [comment]
Could you do another pull and run it with the debug flag on?  This should be on the Python script call.
