### ISSUE TITLE
Error executing start.bat

### ISSUE THREAD

**Issue by Trollmo** [rdeepak2002/reddit-place-script-2022#332]
Logs: 

Exception in thread Thread-1 (task):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\olmor\Downloads\reddit-place-script-2022-main\reddit-place-script-2022-main\main.py", line 710, in task
    next_pixel_placement_time = self.set_pixel_and_check_ratelimit(
  File "C:\Users\olmor\Downloads\reddit-place-script-2022-main\reddit-place-script-2022-main\main.py", line 269, in set_pixel_and_check_ratelimit
    response.json()["errors"][0]["extensions"]["nextAvailablePixelTs"]
KeyError: 'extensions'
Exception in thread Thread-3 (task):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\olmor\Downloads\reddit-place-script-2022-main\reddit-place-script-2022-main\main.py", line 710, in task
    next_pixel_placement_time = self.set_pixel_and_check_ratelimit(
  File "C:\Users\olmor\Downloads\reddit-place-script-2022-main\reddit-place-script-2022-main\main.py", line 269, in set_pixel_and_check_ratelimit
    response.json()["errors"][0]["extensions"]["nextAvailablePixelTs"]
KeyError: 'extensions'
Exception in thread Thread-6 (task):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\olmor\Downloads\reddit-place-script-2022-main\reddit-place-script-2022-main\main.py", line 710, in task
    next_pixel_placement_time = self.set_pixel_and_check_ratelimit(
  File "C:\Users\olmor\Downloads\reddit-place-script-2022-main\reddit-place-script-2022-main\main.py", line 269, in set_pixel_and_check_ratelimit
    response.json()["errors"][0]["extensions"]["nextAvailablePixelTs"]
KeyError: 'extensions'

**Comment by Trollmo** [comment]
Okay, fixed, now What does this means? 

![image](https://user-images.githubusercontent.com/71456058/161449836-5386bcba-f51f-4b8c-9610-a07c4e452acb.png)

**Comment by Skyline-9** [comment]
I think you're getting rate limited when changing IP addresses for Tor (specifically the NEWNYM signal, which is how Tor tells your client to open new circuits)

**Comment by thoroc** [comment]
Debug statement added to check for that: https://github.com/rdeepak2002/reddit-place-script-2022/pull/340

**Comment by Trollmo** [comment]
> I think you're getting rate limited when changing IP addresses for Tor (specifically the NEWNYM signal, which is how Tor tells your client to open new circuits)

So, any fix?

**Comment by thoroc** [comment]
Could you pull and run the verbose version? There should be some logs telling us a bit more just before you get the exception.
