### ISSUE TITLE
Could I get a bit of help?

### ISSUE THREAD

**Issue by jdfrg** [rdeepak2002/reddit-place-script-2022#36]
I get this error when running:
C:\Users\HP\Desktop\reddit-place-script-2022-main>python3 main.py
image size:  (27, 17)
-------Thread #0-------
Refreshing access token...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 410, in task
    access_tokens[credentials_index] = response_data["access_token"]
KeyError: 'access_token'

**Comment by Randomblock1** [comment]
It seems like the credentials you're providing aren't returning an access token.
Make sure you have the username, password, api key, etc. set correctly in .env file.
If you can, enable Verbose Mode in the code and look for "received response:" for more information.

**Comment by jdfrg** [comment]
I created a new app and got it to work, thanks
