### ISSUE TITLE
TypeError: cannot unpack non-iterable int object

### ISSUE THREAD

**Issue by chipqs** [rdeepak2002/reddit-place-script-2022#39]
```
-------Thread #1-------
300 seconds until next pixel is drawn
Got image: https://hot-potato.reddit.com/media/canvas-images/1648890067498-0-f-Aw5FnlTA.png
Exception in thread Thread-11 (task):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Botting\reddit-place-script-2022-main\main.py", line 470, in task
    current_r, current_c, new_rgb = get_unset_pixel(
  File "D:\Botting\reddit-place-script-2022-main\main.py", line 261, in get_unset_pixel
    new_rgb = closest_color(target_rgb, rgb_colors_array)
  File "D:\Botting\reddit-place-script-2022-main\main.py", line 95, in closest_color
    r, g, b = target_rgb
TypeError: cannot unpack non-iterable int object
```
this randomly started happening after restarting the program. didnt change any files.

**Comment by chipqs** [comment]
```
received new access token:  ######################
Getting board
Got image: https://hot-potato.reddit.com/media/canvas-images/1648890528941-0-f-NpiVW01t.png
Exception in thread Thread-11 (task):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Botting\reddit-place-script-2022-main\main.py", line 470, in task
    current_r, current_c, new_rgb = get_unset_pixel(
  File "D:\Botting\reddit-place-script-2022-main\main.py", line 261, in get_unset_pixel
    new_rgb = closest_color(target_rgb, rgb_colors_array)
  File "D:\Botting\reddit-place-script-2022-main\main.py", line 95, in closest_color
    r, g, b = target_rgb
TypeError: cannot unpack non-iterable int object
``` keeps looping till it crashes

**Comment by chipqs** [comment]
any kind of edit to jpg breaks it, i changed mine by a couple of pixels in paint.net and it broke
