### ISSUE TITLE
Someone Please Help

### ISSUE THREAD

**Issue by dustrdz** [rdeepak2002/reddit-place-script-2022#394]
I get a bunch of “requirement already satisfied” 

And then i get this

Traceback (most recent call last):
  File "main.py", line 667, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "main.py", line 661, in main
    client = PlaceClient(config_path=config)
  File "main.py", line 27, in __init__
    self.json_data = utils.get_json_data(self, config_path)
  File "/home/dusty/reddit-place-script-2022/src/utils.py", line 14, in get_json_data
    json_data = json.load(f)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 57 (char 59)

Haven’t been able to get the bot to run, any ideas?

**Comment by NFKRZZ** [comment]
your json file isnt correct, put it in https://jsonlint.com/ and see if it is correctly made.

**Comment by dustrdz** [comment]
> your json file isnt correct, put it in https://jsonlint.com/ and see if it is correctly made.

This is what i have
"image_path": "/home/dusty/reddit-place-script-2022": "image.jpg",

This is what it says
Error: Parse error on line 3:
...t-place-script-2022": "image.jpg",	"im
-----------------------^
Expecting 'EOF', '}', ',', ']', got ':'

**Comment by NFKRZZ** [comment]
if the image file is in the same folder as main.py just put image,jpg and not all that folder stuff
