### ISSUE TITLE
having problems during the installations on MacOS

### ISSUE THREAD

**Issue by xyr3x0** [rdeepak2002/reddit-place-script-2022#404]
Im on MacOS 12.1 and using Python 3.01.4 but while trying to run the start file i get a list of errors:

   Traceback (most recent call last):
  File ".../reddit-place-script-2022-main/main.py", line 677, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File ".../reddit-place-script-2022-main/main.py", line 671, in main
    client = PlaceClient(config_path=config)
  File ".../Downloads/reddit-place-script-2022-main/main.py", line 27, in __init__
    self.json_data = utils.get_json_data(self, config_path)
  File ".../Downloads/reddit-place-script-2022-main/src/utils.py", line 14, in get_json_data
    json_data = json.load(f)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 15 column 37 (char 406) 

how may I fix it?

**Comment by ixi2101** [comment]
It looks like your config is malformed

**Comment by xyr3x0** [comment]
shit you're right, i'm stupid
