### ISSUE TITLE
CI failure

### ISSUE THREAD

**Issue by thoroc** [rdeepak2002/reddit-place-script-2022#413]
the `nox` stage fails on the last 2 PRs: https://github.com/rdeepak2002/reddit-place-script-2022/pull/409 and https://github.com/rdeepak2002/reddit-place-script-2022/pull/408

>Run excitedleigh/setup-nox@v[2](https://github.com/rdeepak2002/reddit-place-script-2022/runs/5816214193?check_suite_focus=true#step:3:2).0.0
[ '2.7.18', '[3](https://github.com/rdeepak2002/reddit-place-script-2022/runs/5816214193?check_suite_focus=true#step:3:3).10.[4](https://github.com/rdeepak2002/reddit-place-script-2022/runs/5816214193?check_suite_focus=true#step:3:4)', '3.6.1[5](https://github.com/rdeepak2002/reddit-place-script-2022/runs/5816214193?check_suite_focus=true#step:3:5)', '3.7.12', '3.8.12', '3.9.12' ] [ '2.7.18', '3.[6](https://github.com/rdeepak2002/reddit-place-script-2022/runs/5816214193?check_suite_focus=true#step:3:6).12', '3.[7](https://github.com/rdeepak2002/reddit-place-script-2022/runs/5816214193?check_suite_focus=true#step:3:7).13', '3.[8](https://github.com/rdeepak2002/reddit-place-script-2022/runs/5816214193?check_suite_focus=true#step:3:8).13', '3.[9](https://github.com/rdeepak2002/reddit-place-script-2022/runs/5816214193?check_suite_focus=true#step:3:9).12' ]
/opt/hostedtoolcache/PyPy/2.7.18/x64
internal/fs/utils.js:269
    throw err;
    ^
>
>Error: EEXIST: file already exists, symlink '/opt/hostedtoolcache/PyPy/2.7.18/x64/bin/pypy' -> '/opt/hostedtoolcache/PyPy/2.7.18/x64/bin/pypy2'
    at Object.symlinkSync (fs.js:[10](https://github.com/rdeepak2002/reddit-place-script-2022/runs/5816214193?check_suite_focus=true#step:3:10)95:3)
    at Object.175 (/home/runner/work/_actions/excitedleigh/setup-nox/v2.0.0/dist/index.js:[14](https://github.com/rdeepak2002/reddit-place-script-2022/runs/5816214193?check_suite_focus=true#step:3:14)59:14)
    at __webpack_require__ (/home/runner/work/_actions/excitedleigh/setup-nox/v2.0.0/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/excitedleigh/setup-nox/v2.0.0/dist/index.js:43:19)
    at /home/runner/work/_actions/excitedleigh/setup-nox/v2.0.0/dist/index.js:47:18
    at Object.<anonymous> (/home/runner/work/_actions/excitedleigh/setup-nox/v2.0.0/dist/index.js:50:10)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  errno: -[17](https://github.com/rdeepak2002/reddit-place-script-2022/runs/5816214193?check_suite_focus=true#step:3:17),
  syscall: 'symlink',
  code: 'EEXIST',
  path: '/opt/hostedtoolcache/PyPy/2.7.[18](https://github.com/rdeepak2002/reddit-place-script-2022/runs/5816214193?check_suite_focus=true#step:3:18)/x64/bin/pypy',
  dest: '/opt/hostedtoolcache/PyPy/2.7.18/x64/bin/pypy2'
}

I have no clue why this is happening.

**Comment by 1101-trash** [comment]
I think you are using 2.7 version of Python. Try to reinstall and download latest python 3  version. Make sure you have all requeriments at the requeirements.txt file (they should have been installed with start.bat/sh)
