### ISSUE TITLE
Line 461 in task access_tokens[credentials_index] = response_data["access_token"]

### ISSUE THREAD

**Issue by Escaleirex** [rdeepak2002/reddit-place-script-2022#47]
Hello, i am getting an error when starting the script on line 461.
Here's the error i am getting:
```
    ~/De/reddit-place-script-2022-main  python3 main.py                ✔ 
image size:  (7, 7)
-------Thread #0-------
Refreshing access token...
Exception in thread Thread-1 (task):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/escaleira/Desktop/reddit-place-script-2022-main/main.py", line 461, in task
    access_tokens[credentials_index] = response_data["access_token"]
KeyError: 'access_token'
```
And here's my .env:
```
ENV_PLACE_USERNAME='["can'tshowthis"]'
ENV_PLACE_PASSWORD='["can'tshowthis"]'
ENV_PLACE_APP_CLIENT_ID='["hWGC-ki958LEDt7P_15EXg"]'
ENV_PLACE_SECRET_KEY='["t5CnJRUMGkA7FC3oXTChj7jUQa4WEw"]'
ENV_DRAW_X_START="856"
ENV_DRAW_Y_START="360"
ENV_R_START='["0"]'
ENV_C_START='["0"]'
```

Can someone help me with this? I am trying to protect the Portuguese flag.

**Comment by Kinomora** [comment]
also having this issue

**Comment by Escaleirex** [comment]
Nice, but my password doesn't have any special characters, my password only contains a uppercase letter. the rest is just numbers and normal letters

**Comment by Escaleirex** [comment]
I Created a new account since mine was from google, and now it works! Thanks for the help @Kinomora.
