### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by NuclearCow** [rdeepak2002/reddit-place-script-2022#48]
Hi. I followed the colour palette in the script but whenever I try to run it the following error pops up.

Exception in thread Thread-4:
Traceback (most recent call last):
File "C:\Users\juliu\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
self.run()
File "C:\Users\juliu\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
self._target(*self._args, **self._kwargs)
File "D:\Tools\reddit-place-script-2022-main\main.py", line 492, in task
current_r, current_c, new_rgb = get_unset_pixel(
File "D:\Tools\reddit-place-script-2022-main\main.py", line 283, in get_unset_pixel
new_rgb = closest_color(target_rgb, rgb_colors_array)
File "D:\Tools\reddit-place-script-2022-main\main.py", line 111, in closest_color
r, g, b = target_rgb
ValueError: too many values to unpack (expected 3)

Any idea how to fix it?

**Comment by esthrshi** [comment]
Your image file is not in the right format. Possible explanations:
1. You are using .png instead of .jpg
2. Your .png format is incorrect, you can use https://convertio.co/ to convert it to the correct .jpg format

**Comment by esthrshi** [comment]
I'm sure Photoshop also has a way of converting it to the right format, but not everyone has Photoshop and I don't know enough about it to know how, maybe someone else does.

**Comment by NuclearCow** [comment]
thanks a lot my dude. found the issue with the source images.
