### ISSUE TITLE
ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by Ali-H-1** [rdeepak2002/reddit-place-script-2022#54]
`Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "F:\reddit-place-script-2022-main\main.py", line 492, in task
    current_r, current_c, new_rgb = get_unset_pixel(
  File "F:\reddit-place-script-2022-main\main.py", line 283, in get_unset_pixel
    new_rgb = closest_color(target_rgb, rgb_colors_array)
  File "F:\reddit-place-script-2022-main\main.py", line 111, in closest_color
    r, g, b = target_rgb
ValueError: too many values to unpack (expected 3)`

**Comment by ediller3** [comment]
Getting this same issue. Any updates?

**Comment by Ali-H-1** [comment]
> Getting this same issue. Any updates?

nope
did u fix it?

**Comment by ediller3** [comment]
Nah i cant figure it out

**Comment by RedOrchid137** [comment]
fixed it by converting .png image to jpg using MS paint. before i just renamed the file but that kinda messed up the image data python expects i think.

**Comment by Ali-H-1** [comment]
> fixed it by converting .png image to jpg using MS paint. before i just renamed the file but that kinda messed up the image data python expects i think.

how did u do that

**Comment by RedOrchid137** [comment]
you can open it in paint, save as image.jpg. that's all there is to it really

**Comment by rdeepak2002** [comment]
Closing issue since it was due to image format. Also I believe support for png has been recently added by a contributor.
