### ISSUE TITLE
Please Help me

### ISSUE THREAD

**Issue by Lothar1812** [rdeepak2002/reddit-place-script-2022#86]
First, Thank you very much!

Exception in thread Thread-1 (task):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "D:\reddit-place-script-2022-main\reddit-place-script-2022-main\main.py", line 425, in task
    current_r, current_c, new_rgb = get_unset_pixel(
  File "D:\reddit-place-script-2022-main\reddit-place-script-2022-main\main.py", line 222, in get_unset_pixel
    if pix2[x + pixel_x_start, y + pixel_y_start] != new_rgb:
IndexError: image index out of range

I didnt changed the normal image, can you please help me?

**Comment by martan712** [comment]
you are trying to draw on the newly added board, this is not yet supported see #73
