### ISSUE TITLE
[BUG] TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by 22tooty2** [rdeepak2002/reddit-place-script-2022#91]
When trying to run the bot.

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "G:\.Relevent\PLACE\versions\2\reddit-place-script-2022-main\main.py", line 432, in task
    current_r, current_c, new_rgb = get_unset_pixel(
  File "G:\.Relevent\PLACE\versions\2\reddit-place-script-2022-main\main.py", line 223, in get_unset_pixel
    new_rgb = closest_color(target_rgb, rgb_colors_array)
  File "G:\.Relevent\PLACE\versions\2\reddit-place-script-2022-main\main.py", line 45, in closest_color
    r, g, b = target_rgb[:3]  # trim rgba tuple to rgb if png
TypeError: 'int' object is not subscriptable

**Comment by somekindofmadz** [comment]
same here, any solution yet?

**Comment by somekindofmadz** [comment]
> same here, any solution yet?

Having jpg image instead of png as a refference solved it for me

**Comment by thoroc** [comment]
Should be fixed with https://github.com/rdeepak2002/reddit-place-script-2022/pull/250. Closing for now. Feel free to re-open if you are still encountering the issue.
